#!/bin/bash

# fetches artist, title from kölncampus.com, prepends timestring,
# writes to ./kc/kc.log
campus() {

    dir=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
    cd "$dir"

	if [ -z "$1" ]; then
		curl https://www.koelncampus.com/sender/livestream/ \
                | grep id='"'currentSong'[TA]' \
                | sed -e 's/<[^>]*>//g' \
                | awk '{print $1,$2,$3,$4,$5,$6,$7,$8}' \
                | while IFS= read -r line; do 
                	printf '[%s] %s\n' \
                	"$(date '+%Y-%m-%d %H:%M:%S')" \
                	"$line";
                  done \
                | tee -a ./kc.log
        echo "success!"
    else
    	case "$1" in
	        list)
                case "$2" in
                    artists)
                        cat ./kc.log \
                            | awk 'NR % 2 ==1'
                        ;;
                    songs)
                        cat ./kc.log \
                            | awk 'NR %2 ==0'
                        ;;
                    *)
                        cat ./kc.log
                esac
	            ;;
	        artist)
	            curl https://www.koelncampus.com/sender/livestream/ \
	                | grep id='"'currentSong'[A]' \
	                | sed -e 's/<[^>]*>//g' \
	                | awk '{print $1,$2,$3,$4,$5,$6,$7,$8}'

	            ;;
	        song)
	            curl https://www.koelncampus.com/sender/livestream/ \
	                | grep id='"'currentSong'[T]' \
	                | sed -e 's/<[^>]*>//g' \
	                | awk '{print $1,$2,$3,$4,$5,$6,$7,$8}'
	            ;;            
	        listartists)
	            cat ./kc.log \
	                | awk 'NR % 2 ==1'
	            ;;
	        listsongs)
	            cat ./kc.log \
	                | awk 'NR % 2 ==0'
	            ;;
	        *)
	         echo "Sorry, i did not understand that"
    	esac
   	fi
}

campus "$1""$2"

